title: Si-Jin Guo
logo: /logo.png
email: jguo2001@berkeley.edu
description: SJ is a student and researcher affiliated with Columbia University Irving Medical Centre and the University of California, Berkeley. He is currently working on a project to improve and destigmatize intersex healthcare
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

